const mockData = {
  jobs_bacula: [
    {
      nome_job: "Alpha-DC",
      cliente: "ServidorA1",
      ip: "192.168.10.11",
      horario_agendado: "01:00:00",
      file_set: "C:\\Backup\\Alpha",
      status: "true",
      retencao_diff: "6 dias",
      retencao_full: "3 semanas",
      empresa: "AlphaTech",
      data_criacao: "2025-08-20T10:35:00Z",
    },
    {
      nome_job: "Alpha-DB",
      cliente: "ServidorA2",
      ip: "192.168.10.12",
      horario_agendado: "02:00:00",
      file_set: "C:\\Backup\\FileServer\\Docs;C:\\Backup\\FileServer\\Finance",
      status: "false",
      retencao_diff: "6 dias",
      retencao_full: "3 semanas",
      empresa: "AlphaTech",
      data_criacao: "2025-08-20T12:35:00Z",
    },
    {
      nome_job: "Alpha-Mail",
      cliente: "ServidorA3",
      ip: "192.168.10.13",
      horario_agendado: "03:00:00",
      file_set: "C:\\Backup\\AlphaMail",
      status: "true",
      retencao_diff: "6 dias",
      retencao_full: "3 semanas",
      empresa: "AlphaTech",
      data_criacao: "2025-08-20T13:35:00Z",
    },
    {
      nome_job: "Alpha-Web",
      cliente: "ServidorA4",
      ip: "192.168.10.14",
      horario_agendado: "04:00:00",
      file_set: "C:\\Backup\\AlphaWeb",
      status: "true",
      retencao_diff: "6 dias",
      retencao_full: "3 semanas",
      empresa: "AlphaTech",
      data_criacao: "2025-09-20T09:35:30Z",
    },
    {
      nome_job: "Alpha-ERP",
      cliente: "ServidorA5",
      ip: "192.168.10.15",
      horario_agendado: "05:00:00",
      file_set: "C:\\Backup\\AlphaERP",
      status: "false",
      retencao_diff: "6 dias",
      retencao_full: "3 semanas",
      empresa: "AlphaTech",
      data_criacao: "2025-09-20T10:35:10Z",
    },
    {
      nome_job: "Alpha-CRM",
      cliente: "ServidorA6",
      ip: "192.168.10.16",
      horario_agendado: "06:00:00",
      file_set: "C:\\Backup\\AlphaCRM",
      status: "true",
      retencao_diff: "6 dias",
      retencao_full: "3 semanas",
      empresa: "AlphaTech",
      data_criacao: "2025-09-20T10:55:20Z",
    },
    {
      nome_job: "Alpha-Backup1",
      cliente: "ServidorA7",
      ip: "192.168.10.17",
      horario_agendado: "07:00:00",
      file_set: "C:\\Backup\\FileServer\\Docs;C:\\Backup\\FileServer\\Finance",
      status: "true",
      retencao_diff: "6 dias",
      retencao_full: "3 semanas",
      empresa: "AlphaTech",
      data_criacao: "2025-09-20T15:55:30Z",
    },
    {
      nome_job: "Alpha-Backup2",
      cliente: "ServidorA8",
      ip: "192.168.10.18",
      horario_agendado: "08:00:00",
      file_set: "C:\\Backup\\AlphaB2",
      status: "false",
      retencao_diff: "6 dias",
      retencao_full: "3 semanas",
      empresa: "AlphaTech",
      data_criacao: "2025-09-21T10:55:00Z",
    },

    {
      nome_job: "Beta-DC",
      cliente: "ServidorB1",
      ip: "192.168.20.11",
      horario_agendado: "00:30:00",
      file_set: "D:\\Backups\\Beta",
      status: "true",
      retencao_diff: "7 dias",
      retencao_full: "1 mês",
      empresa: "BetaCorp",
      data_criacao: "2025-10-21T10:55:00Z",
    },
    {
      nome_job: "Beta-ERP",
      cliente: "ServidorB2",
      ip: "192.168.20.12",
      horario_agendado: "01:30:00",
      file_set: "D:\\;D:\\Backup\\ImportantConfigs;D:\\Backup\\Applications;",
      status: "true",
      retencao_diff: "7 dias",
      retencao_full: "1 mês",
      empresa: "BetaCorp",
      data_criacao: "2025-10-22T10:55:00Z",
    },
    {
      nome_job: "Beta-Web",
      cliente: "ServidorB3",
      ip: "192.168.20.13",
      horario_agendado: "02:30:00",
      file_set: "D:\\Backups\\BetaWeb",
      status: "false",
      retencao_diff: "7 dias",
      retencao_full: "1 mês",
      empresa: "BetaCorp",
      data_criacao: "2025-10-22T11:55:00Z",
    },
    {
      nome_job: "Beta-CRM",
      cliente: "ServidorB4",
      ip: "192.168.20.14",
      horario_agendado: "03:30:00",
      file_set: "D:\\Backups\\BetaCRM",
      status: "true",
      retencao_diff: "7 dias",
      retencao_full: "1 mês",
      empresa: "BetaCorp",
      data_criacao: "2025-10-22T13:35:10Z",
    },
    {
      nome_job: "Beta-Mail",
      cliente: "ServidorB5",
      ip: "192.168.20.15",
      horario_agendado: "04:30:00",
      file_set: "D:\\Windows\\Temp;-D:\\ProgramData\\Temp",
      status: "true",
      retencao_diff: "7 dias",
      retencao_full: "1 mês",
      empresa: "BetaCorp",
      data_criacao: "2025-10-22T14:35:10Z",
    },
    {
      nome_job: "Beta-Backup1",
      cliente: "ServidorB6",
      ip: "192.168.20.16",
      horario_agendado: "05:30:00",
      file_set: "D:\\Backups\\BetaB1",
      status: "false",
      retencao_diff: "7 dias",
      retencao_full: "1 mês",
      empresa: "BetaCorp",
      data_criacao: "2025-10-22T14:55:10Z",
    },
    {
      nome_job: "Beta-Backup2",
      cliente: "ServidorB7",
      ip: "192.168.20.17",
      horario_agendado: "06:30:00",
      file_set: "D:\\Backups\\BetaB2",
      status: "true",
      retencao_diff: "7 dias",
      retencao_full: "1 mês",
      empresa: "BetaCorp",
      data_criacao: "2025-10-23T14:35:10Z",
    },
    {
      nome_job: "Beta-Backup3",
      cliente: "ServidorB8",
      ip: "192.168.20.18",
      horario_agendado: "07:30:00",
      file_set: "D:\\Backups\\BetaB3",
      status: "true",
      retencao_diff: "7 dias",
      retencao_full: "1 mês",
      empresa: "BetaCorp",
      data_criacao: "2025-10-23T15:20:10Z",
    },

    {
      nome_job: "Cyber-DC",
      cliente: "ServidorC1",
      ip: "192.168.20.10",
      horario_agendado: "00:30:00",
      file_set: "C:\\Backup\\Cyber",
      status: "true",
      retencao_diff: "5 dias",
      retencao_full: "2 Semanas",
      empresa: "CyberNet Solutions",
      data_criacao: "2025-10-24T09:20:10Z",
    },
    {
      nome_job: "Cyber-Web",
      cliente: "ServidorC2",
      ip: "192.168.20.11",
      horario_agendado: "02:00:00",
      file_set: "C:\\Backup\\CyberWeb",
      status: "false",
      retencao_diff: "7 dias",
      retencao_full: "1 Mês",
      empresa: "CyberNet Solutions",
      data_criacao: "2025-10-24T10:20:10Z",
    },
    {
      nome_job: "Cyber-Mail",
      cliente: "ServidorC3",
      ip: "192.168.20.12",
      horario_agendado: "03:15:00",
      file_set: "C:\\Backup\\CyberMail\\Backup\\Applications",
      status: "true",
      retencao_diff: "6 dias",
      retencao_full: "3 Semanas",
      empresa: "CyberNet Solutions",
      data_criacao: "2025-10-24T12:10:00Z",
    },
    {
      nome_job: "Cyber-Dev",
      cliente: "ServidorC4",
      ip: "192.168.20.13",
      horario_agendado: "04:00:00",
      file_set: "C:\\Backup\\CyberDev",
      status: "true",
      retencao_diff: "10 dias",
      retencao_full: "1 Mês",
      empresa: "CyberNet Solutions",
      data_criacao: "2025-10-24T14:10:00Z",
    },
    {
      nome_job: "Cyber-DB",
      cliente: "ServidorC5",
      ip: "192.168.20.14",
      horario_agendado: "05:30:00",
      file_set: "C:\\Backup\\CyberDB",
      status: "false",
      retencao_diff: "5 dias",
      retencao_full: "2 Semanas",
      empresa: "CyberNet Solutions",
      data_criacao: "2025-10-24T16:10:00Z",
    },
    {
      nome_job: "Data-DC",
      cliente: "ServidorD1",
      ip: "192.168.30.10",
      horario_agendado: "01:10:00",
      file_set: "C:\\Backup\\Data",
      status: "true",
      retencao_diff: "7 dias",
      retencao_full: "2 Semanas",
      empresa: "DataSafe Corp",
      data_criacao: "2025-10-24T17:10:00Z",
    },
    {
      nome_job: "Data-ERP",
      cliente: "ServidorD2",
      ip: "192.168.30.11",
      horario_agendado: "02:45:00",
      file_set:
        "C:\\Backup\\Database\\PostgreSQL\\Data;C:\\Backup\\Database\\MySQL",
      status: "true",
      retencao_diff: "5 dias",
      retencao_full: "1 Mês",
      empresa: "DataSafe Corp",
      data_criacao: "2025-10-25T10:10:00Z",
    },
    {
      nome_job: "Data-Mail",
      cliente: "ServidorD3",
      ip: "192.168.30.12",
      horario_agendado: "03:50:00",
      file_set: "C:\\Backup\\DataMail",
      status: "false",
      retencao_diff: "6 dias",
      retencao_full: "3 Semanas",
      empresa: "DataSafe Corp",
      data_criacao: "2025-10-25T12:10:00Z",
    },
    {
      nome_job: "Data-Analytics",
      cliente: "ServidorD4",
      ip: "192.168.30.13",
      horario_agendado: "04:20:00",
      file_set: "C:\\Backup\\DataAnalytics",
      status: "true",
      retencao_diff: "9 dias",
      retencao_full: "1 Mês",
      empresa: "DataSafe Corp",
      data_criacao: "2025-10-25T13:10:00Z",
    },
    {
      nome_job: "Data-DB",
      cliente: "ServidorD5",
      ip: "192.168.30.14",
      horario_agendado: "05:40:00",
      file_set: "C:\\Backup\\DataDB",
      status: "true",
      retencao_diff: "4 dias",
      retencao_full: "2 Semanas",
      empresa: "DataSafe Corp",
      data_criacao: "2025-10-25T15:10:00Z",
    },
  ],

  bacula_jobs_execucoes: [
    {
      job_id: 1,
      nome_job: "Cyber-DC",
      cliente: "ServidorC1",
      horario_agendado: "00:30:00",
      horario_inicio: "00:30:05",
      horario_fim: "00:40:00",
      tamanho: "8.4 GB",
      status_final: "OK",
      empresa: "CyberNet Solutions",
    },
    {
      job_id: 2,
      nome_job: "Cyber-DC",
      cliente: "ServidorC1",
      horario_agendado: "00:30:00",
      horario_inicio: "00:30:10",
      horario_fim: "00:35:00",
      tamanho: "2.1 GB",
      status_final: "FALHA",
      empresa: "CyberNet Solutions",
    },
    {
      job_id: 3,
      nome_job: "Cyber-Web",
      cliente: "ServidorC2",
      horario_agendado: "02:00:00",
      horario_inicio: "02:00:10",
      horario_fim: "02:05:00",
      tamanho: "0 GB",
      status_final: "FALHA",
      empresa: "CyberNet Solutions",
    },
    {
      job_id: 4,
      nome_job: "Cyber-Mail",
      cliente: "ServidorC3",
      horario_agendado: "03:15:00",
      horario_inicio: "03:15:05",
      horario_fim: "03:25:10",
      tamanho: "5.2 GB",
      status_final: "OK",
      empresa: "CyberNet Solutions",
    },
    {
      job_id: 5,
      nome_job: "Cyber-Dev",
      cliente: "ServidorC4",
      horario_agendado: "04:00:00",
      horario_inicio: "04:00:15",
      horario_fim: "04:15:30",
      tamanho: "12.0 GB",
      status_final: "OK",
      empresa: "CyberNet Solutions",
    },
    {
      job_id: 6,
      nome_job: "Cyber-Dev",
      cliente: "ServidorC4",
      horario_agendado: "04:00:00",
      horario_inicio: "04:16:00",
      horario_fim: "04:20:00",
      tamanho: "0.8 GB",
      status_final: "FALHA",
      empresa: "CyberNet Solutions",
    },
    {
      job_id: 7,
      nome_job: "Cyber-DB",
      cliente: "ServidorC5",
      horario_agendado: "05:30:00",
      horario_inicio: "05:30:20",
      horario_fim: "05:31:00",
      tamanho: "0 GB",
      status_final: "FALHA",
      empresa: "CyberNet Solutions",
    },
    {
      job_id: 8,
      nome_job: "Cyber-DB",
      cliente: "ServidorC5",
      horario_agendado: "05:30:00",
      horario_inicio: "05:31:05",
      horario_fim: "05:40:00",
      tamanho: "10.3 GB",
      status_final: "OK",
      empresa: "CyberNet Solutions",
    },
    {
      job_id: 1,
      nome_job: "Data-DC",
      cliente: "ServidorD1",
      horario_agendado: "01:10:00",
      horario_inicio: "01:10:05",
      horario_fim: "01:15:00",
      tamanho: "9.5 GB",
      status_final: "OK",
      empresa: "DataSafe Corp",
    },
    {
      job_id: 2,
      nome_job: "Data-ERP",
      cliente: "ServidorD2",
      horario_agendado: "02:45:00",
      horario_inicio: "02:45:15",
      horario_fim: "02:50:30",
      tamanho: "4.7 GB",
      status_final: "OK",
      empresa: "DataSafe Corp",
    },
    {
      job_id: 3,
      nome_job: "Data-ERP",
      cliente: "ServidorD2",
      horario_agendado: "02:45:00",
      horario_inicio: "02:51:00",
      horario_fim: "02:53:00",
      tamanho: "1.1 GB",
      status_final: "FALHA",
      empresa: "DataSafe Corp",
    },
    {
      job_id: 4,
      nome_job: "Data-Mail",
      cliente: "ServidorD3",
      horario_agendado: "03:50:00",
      horario_inicio: "03:50:10",
      horario_fim: "03:51:00",
      tamanho: "0 GB",
      status_final: "FALHA",
      empresa: "DataSafe Corp",
    },
    {
      job_id: 5,
      nome_job: "Data-Analytics",
      cliente: "ServidorD4",
      horario_agendado: "04:20:00",
      horario_inicio: "04:20:05",
      horario_fim: "04:25:00",
      tamanho: "6.3 GB",
      status_final: "OK",
      empresa: "DataSafe Corp",
    },
    {
      job_id: 6,
      nome_job: "Data-DB",
      cliente: "ServidorD5",
      horario_agendado: "05:40:00",
      horario_inicio: "05:40:15",
      horario_fim: "05:45:30",
      tamanho: "10.9 GB",
      status_final: "OK",
      empresa: "DataSafe Corp",
    },
    {
      job_id: 7,
      nome_job: "Data-DB",
      cliente: "ServidorD5",
      horario_agendado: "05:40:00",
      horario_inicio: "05:46:00",
      horario_fim: "05:48:00",
      tamanho: "2.2 GB",
      status_final: "FALHA",
      empresa: "DataSafe Corp",
    },
    {
      job_id: 8,
      nome_job: "Data-DB",
      cliente: "ServidorD5",
      horario_agendado: "05:40:00",
      horario_inicio: "05:49:00",
      horario_fim: "05:55:00",
      tamanho: "11.0 GB",
      status_final: "OK",
      empresa: "DataSafe Corp",
    },

    {
      job_id: 1,
      nome_job: "Alpha-DC",
      cliente: "ServidorA1",
      horario_agendado: "01:00:00",
      horario_inicio: "01:00:10",
      horario_fim: "01:12:05",
      tamanho: "12.5 GB",
      status_final: "OK",
      empresa: "AlphaTech",
    },
    {
      job_id: 2,
      nome_job: "Alpha-DB",
      cliente: "ServidorA2",
      horario_agendado: "02:00:00",
      horario_inicio: "02:00:20",
      horario_fim: "02:15:45",
      tamanho: "8.2 GB",
      status_final: "OK",
      empresa: "AlphaTech",
    },
    {
      job_id: 3,
      nome_job: "Alpha-Mail",
      cliente: "ServidorA3",
      horario_agendado: "03:00:00",
      horario_inicio: "03:00:30",
      horario_fim: "03:09:15",
      tamanho: "5.1 GB",
      status_final: "FALHA",
      empresa: "AlphaTech",
    },
    {
      job_id: 4,
      nome_job: "Alpha-Web",
      cliente: "ServidorA4",
      horario_agendado: "04:00:00",
      horario_inicio: "04:00:15",
      horario_fim: "04:14:40",
      tamanho: "10.7 GB",
      status_final: "OK",
      empresa: "AlphaTech",
    },
    {
      job_id: 5,
      nome_job: "Alpha-ERP",
      cliente: "ServidorA5",
      horario_agendado: "05:00:00",
      horario_inicio: "05:00:10",
      horario_fim: "05:18:05",
      tamanho: "20.5 GB",
      status_final: "OK",
      empresa: "AlphaTech",
    },
    {
      job_id: 6,
      nome_job: "Alpha-CRM",
      cliente: "ServidorA6",
      horario_agendado: "06:00:00",
      horario_inicio: "06:00:25",
      horario_fim: "06:16:55",
      tamanho: "7.4 GB",
      status_final: "FALHA",
      empresa: "AlphaTech",
    },
    {
      job_id: 7,
      nome_job: "Alpha-Backup1",
      cliente: "ServidorA7",
      horario_agendado: "07:00:00",
      horario_inicio: "07:00:30",
      horario_fim: "07:19:20",
      tamanho: "14.9 GB",
      status_final: "OK",
      empresa: "AlphaTech",
    },
    {
      job_id: 8,
      nome_job: "Alpha-Backup2",
      cliente: "ServidorA8",
      horario_agendado: "08:00:00",
      horario_inicio: "08:00:35",
      horario_fim: "08:20:50",
      tamanho: "16.3 GB",
      status_final: "OK",
      empresa: "AlphaTech",
    },

    {
      job_id: 9,
      nome_job: "Beta-DC",
      cliente: "ServidorB1",
      horario_agendado: "00:30:00",
      horario_inicio: "00:30:10",
      horario_fim: "00:45:25",
      tamanho: "11.0 GB",
      status_final: "OK",
      empresa: "BetaCorp",
    },
    {
      job_id: 10,
      nome_job: "Beta-ERP",
      cliente: "ServidorB2",
      horario_agendado: "01:30:00",
      horario_inicio: "01:30:20",
      horario_fim: "01:48:40",
      tamanho: "18.3 GB",
      status_final: "OK",
      empresa: "BetaCorp",
    },
    {
      job_id: 11,
      nome_job: "Beta-Web",
      cliente: "ServidorB3",
      horario_agendado: "02:30:00",
      horario_inicio: "02:30:15",
      horario_fim: "02:49:05",
      tamanho: "13.7 GB",
      status_final: "FALHA",
      empresa: "BetaCorp",
    },
    {
      job_id: 12,
      nome_job: "Beta-CRM",
      cliente: "ServidorB4",
      horario_agendado: "03:30:00",
      horario_inicio: "03:30:25",
      horario_fim: "03:52:15",
      tamanho: "9.9 GB",
      status_final: "OK",
      empresa: "BetaCorp",
    },
    {
      job_id: 13,
      nome_job: "Beta-Mail",
      cliente: "ServidorB5",
      horario_agendado: "04:30:00",
      horario_inicio: "04:30:10",
      horario_fim: "04:50:40",
      tamanho: "7.6 GB",
      status_final: "OK",
      empresa: "BetaCorp",
    },
    {
      job_id: 14,
      nome_job: "Beta-Backup1",
      cliente: "ServidorB6",
      horario_agendado: "05:30:00",
      horario_inicio: "05:30:30",
      horario_fim: "05:58:00",
      tamanho: "19.1 GB",
      status_final: "FALHA",
      empresa: "BetaCorp",
    },
    {
      job_id: 15,
      nome_job: "Beta-Backup2",
      cliente: "ServidorB7",
      horario_agendado: "06:30:00",
      horario_inicio: "06:30:15",
      horario_fim: "06:57:45",
      tamanho: "15.4 GB",
      status_final: "OK",
      empresa: "BetaCorp",
    },
    {
      job_id: 16,
      nome_job: "Beta-Backup3",
      cliente: "ServidorB8",
      horario_agendado: "07:30:00",
      horario_inicio: "07:30:20",
      horario_fim: "07:55:35",
      tamanho: "10.8 GB",
      status_final: "OK",
      empresa: "BetaCorp",
    },
    {
      job_id: 1,
      nome_job: "Alpha-DC",
      cliente: "ServidorA1",
      horario_agendado: "01:00:00",
      horario_inicio: "01:00:10",
      horario_fim: "01:12:05",
      tamanho: "12.5 GB",
      status_final: "OK",
      empresa: "AlphaTech",
    },
    {
      job_id: 1,
      nome_job: "Alpha-DC",
      cliente: "ServidorA1",
      horario_agendado: "01:00:00",
      horario_inicio: "01:00:15",
      horario_fim: "01:11:00",
      tamanho: "11.9 GB",
      status_final: "FALHA",
      empresa: "AlphaTech",
    },
    {
      job_id: 1,
      nome_job: "Alpha-DC",
      cliente: "ServidorA1",
      horario_agendado: "01:00:00",
      horario_inicio: "01:00:12",
      horario_fim: "01:10:30",
      tamanho: "12.2 GB",
      status_final: "OK",
      empresa: "AlphaTech",
    },

    {
      job_id: 2,
      nome_job: "Alpha-DB",
      cliente: "ServidorA2",
      horario_agendado: "02:00:00",
      horario_inicio: "02:00:20",
      horario_fim: "02:15:45",
      tamanho: "8.2 GB",
      status_final: "OK",
      empresa: "AlphaTech",
    },
    {
      job_id: 2,
      nome_job: "Alpha-DB",
      cliente: "ServidorA2",
      horario_agendado: "02:00:00",
      horario_inicio: "02:00:25",
      horario_fim: "02:16:00",
      tamanho: "8.0 GB",
      status_final: "FALHA",
      empresa: "AlphaTech",
    },

    {
      job_id: 10,
      nome_job: "Beta-ERP",
      cliente: "ServidorB2",
      horario_agendado: "01:30:00",
      horario_inicio: "01:30:20",
      horario_fim: "01:48:40",
      tamanho: "18.3 GB",
      status_final: "OK",
      empresa: "BetaCorp",
    },
    {
      job_id: 10,
      nome_job: "Beta-ERP",
      cliente: "ServidorB2",
      horario_agendado: "01:30:00",
      horario_inicio: "01:30:25",
      horario_fim: "01:47:50",
      tamanho: "17.9 GB",
      status_final: "FALHA",
      empresa: "BetaCorp",
    },
  ],
};

export const supabase = {
  from(tableName) {
    return {
      select() {
        return new Promise((resolve) => {
          const data = mockData[tableName] || [];
          resolve({ data, error: null });
        });
      },
    };
  },
};
